#include "pipe/protocol.hpp"
#include "protocol/protocol.hpp"

#include <cstdlib>
#include <iostream>
#include <string_view>

namespace client = llavon::ime::protocol;
namespace server = ime::unix_service::protocol;

namespace {
client::ByteVector unhex(std::string_view hex) {
    client::ByteVector bytes;
    const auto nibble = [](char digit) { return digit <= '9' ? digit - '0' : digit - 'a' + 10; };
    for (std::size_t i = 0; i < hex.size(); i += 2)
        bytes.push_back(static_cast<std::uint8_t>(16 * nibble(hex[i]) + nibble(hex[i + 1])));
    return bytes;
}

bool all_message_golden_tests() {
    client::SessionId id{}; id[0] = 1;
    client::ServiceEpoch epoch{}; epoch[0] = 2;
    client::RecordCommitRequest record;
    record.event_id = id; record.source_id = epoch; record.context = u"A"; record.answer = u"你!";
    record.entries = {{u"ㄋㄧˇ", U'你', true, false}, {u"", U'!', false, true}};
    const std::vector<client::Message> messages{
        client::OpenSessionRequest{}, client::OpenSessionResponse{id, epoch},
        client::PredictRequest{id, 3, 4, u"A", {client::PaddingEntry(U'你'), client::PaddingEntry(std::u16string(u"ㄋㄧˇ"))}},
        client::Prediction{id, 3, 4, {{U'你', U'擬'}}}, client::CloseSessionRequest{id}, client::CloseSessionResponse{id, true},
        client::StatusRequest{std::nullopt}, client::StatusRequest{id},
        client::StatusResponse{epoch, false, true, 1, 8, client::SessionStatus{id, true, false, true, 3}},
        client::ShutdownRequest{}, client::ShutdownResponse{true},
        client::Error{client::ErrorCode::ResourceExhausted, id, 3, 4, "busy"}, record,
        client::RecordCommitResponse{id, true}, client::DiscardCommitRequest{id}, client::DiscardCommitResponse{id, true}};
    // Captured from the released, pre-consolidation codec, not generated by
    // the implementation under test. Both request and response forms are frozen.
    const std::vector<std::string_view> golden{
        "020000000100",
        "2200000001010100000000000000000000000000000002000000000000000000000000000000",
        "3b0000000201000000000000000000000000000000030000000000000004000000000000000100000041000200000001604f000000030000000b312731c702",
        "310000000301000000000000000000000000000000030000000000000004000000000000000100000002000000604f0000ec640000",
        "12000000040001000000000000000000000000000000",
        "1300000004010100000000000000000000000000000001",
        "03000000050000",
        "1300000005000101000000000000000000000000000000",
        "380000000501020000000000000000000000000000000001010000000800000001010000000000000000000000000000000100010300000000000000",
        "020000000600", "03000000060101",
        "2a000000070701000000000000000000000000000000030000000000000004000000000000000400000062757379",
        "4e0000000800010000000000000000000000000000000200000000000000000000000000000001000000410002000000604f210002000000030000000b312731c702604f0000010000000000210000000001",
        "1300000008010100000000000000000000000000000001",
        "12000000090001000000000000000000000000000000",
        "1300000009010100000000000000000000000000000001"};
    for (std::size_t i = 0; i < messages.size(); ++i) {
        const auto bytes = unhex(golden[i]);
        if (client::encode(messages[i]) != bytes || server::encode(server::decode(bytes)) != bytes ||
            client::decode(bytes).index() != messages[i].index()) return false;
        for (std::size_t length = 0; length < bytes.size(); ++length) {
            bool rejected = false;
            try { (void)client::decode(client::ByteVector(bytes.begin(), bytes.begin() + static_cast<std::ptrdiff_t>(length))); }
            catch (const client::ProtocolError&) { rejected = true; }
            if (!rejected) return false;
        }
        auto trailing = bytes;
        trailing.push_back(0);
        ++trailing[0];
        bool rejected = false;
        try { (void)client::decode(trailing); } catch (const client::ProtocolError&) { rejected = true; }
        if (!rejected) return false;
    }
    return true;
}
}

int main() {
    if (!all_message_golden_tests()) return EXIT_FAILURE;
    client::PredictRequest request;
    for (std::size_t i = 0; i < request.session_id.size(); ++i)
        request.session_id[i] = static_cast<std::uint8_t>(i + 1);
    request.request_id = 0x0102030405060708ULL;
    request.buffer_revision = 0x1112131415161718ULL;
    request.context = u"你";
    request.padding = {client::PaddingEntry(U'好'), client::PaddingEntry(std::u16string(u"ㄋㄧˇ"))};
    // Frozen pre-refactor wire format: both tag-1 and tag-0 padding positions.
    const client::ByteVector golden{
        59, 0, 0, 0, 2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
        8, 7, 6, 5, 4, 3, 2, 1, 24, 23, 22, 21, 20, 19, 18, 17, 1, 0, 0, 0,
        96, 79, 2, 0, 0, 0, 1, 125, 89, 0, 0, 0, 3, 0, 0, 0, 11, 49, 39, 49, 199, 2};
    if (client::encode(request) != golden) return EXIT_FAILURE;
    const auto decoded = std::get<server::PredictRequest>(server::decode(golden));
    if (decoded.context != request.context || decoded.request_id != request.request_id ||
        decoded.buffer_revision != request.buffer_revision || decoded.padding.size() != 2 ||
        !decoded.padding[0].chosen() || decoded.padding[0].chosen_char() != U'好' ||
        decoded.padding[1].chosen() || decoded.padding[1].bopomofo() != u"ㄋㄧˇ" ||
        server::encode(decoded) != golden) return EXIT_FAILURE;
    const auto returned = std::get<client::PredictRequest>(client::decode(server::encode(decoded)));
    if (returned.session_id != request.session_id) return EXIT_FAILURE;
    for (const char32_t invalid : {char32_t{0}, char32_t{0xd800}, char32_t{0x110000}}) {
        request.padding = {client::PaddingEntry(invalid)};
        auto bad = decoded;
        bad.padding = request.padding;
        bool client_rejected = false, server_rejected = false;
        try { (void)client::encode(request); } catch (const client::ProtocolError&) { client_rejected = true; }
        try { (void)server::encode(bad); } catch (const server::ProtocolError&) { server_rejected = true; }
        if (!client_rejected || !server_rejected) return EXIT_FAILURE;
    }
    std::cout << "client/service golden wire compatibility passed\n";
    return EXIT_SUCCESS;
}
