"""Regenerate the embedded mixed-input lexicon (no Python dependency at runtime).

Requires wordfreq==3.1.1 and opencc-python-reimplemented==0.1.7.
Data licensing and provenance: ../data/README.md.
"""

import math
import re
from pathlib import Path

from opencc import OpenCC
from wordfreq import get_frequency_dict


def main():
    converter = OpenCC("s2twp")
    entries = {}
    for language in ("en", "zh"):
        for word, frequency in get_frequency_dict(language, wordlist="large").items():
            zipf = math.log10(frequency) + 9
            if language == "en":
                if zipf < 3 or not re.fullmatch(r"[a-z][a-z0-9]*(?:['-][a-z0-9]+)*", word):
                    continue
            else:
                if zipf < 2.5 or not re.fullmatch(r"[\u4e00-\u9fff]{1,4}", word):
                    continue
                word = converter.convert(word)
            entries[word] = max(entries.get(word, 0), round(zipf * 100))

    output = Path(__file__).resolve().parents[1] / "data" / "mixed_lexicon.inc"
    # Small raw literals avoid the C++ minimum string-literal length limit.
    lines = ["// Generated by tools/generate_mixed_lexicon.py; CC BY-SA 4.0.",
             "// See data/README.md for attribution and transformations."]
    batch = ""
    for word, zipf in sorted(entries.items()):
        record = f"{word}\t{zipf}\n"
        if len((batch + record).encode()) > 3500:
            lines.append('std::string_view{R"lex(' + batch + ')lex", ' + str(len(batch.encode())) + '},')
            batch = ""
        batch += record
    if batch:
        lines.append('std::string_view{R"lex(' + batch + ')lex", ' + str(len(batch.encode())) + '},')
    output.write_text("\n".join(lines) + "\n")
    print(f"{len(entries)} entries, {output.stat().st_size} bytes")


if __name__ == "__main__":
    main()
